### ISSUE TITLE
pulgin load error

### ISSUE THREAD

**Issue by knwin** [modzy/Modzy-QGIS-Plugin#1]
I am using QGIS 3.22 and 3.24. When I turn on Modzy plugin I got following error and plugin is not shown in the processing toolbox.
" **Couldn't load plugin 'Modzy' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'modzy'** 
"

**Comment by knwin** [comment]
I am using Osgeo4W installer and now I install modzy-sdk as follow and the plug-in is working. Sorry for early panic reporting.

C:\OSGeo4W\apps\Python39>pip install modzy-sdk

**Comment by caradoxical** [comment]
BTW @knwin let us know if you're having any trouble using the plug-in or getting valid results from the Vehicle Detection model. We'd be happy to help. Thanks again for trying out our plug-in!
